version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt  # MkDocs 依赖文件

mkdocs:
  configuration: mkdocs.yml  # 指定 MkDocs 配置文件

formats:
  - htmlzip  # 生成可下载的 HTML 压缩包
  - pdf      # 生成 PDF 格式文档
  - epub     # 生成 EPUB 电子书
