version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt  # MkDocs 依赖文件

mkdocs:
  configuration: mkdocs.yml  # 指定 MkDocs 配置文件

formats:
  - html  # 只生成 HTML 格式

